In [1]:
# INDEXCATION
# Let A be the matrix,  then A[row, col];
# A[row, :] - every element of the given row
# A[: ,col] - every element of the given column

In [3]:
import numpy as np
mydata = np.arange(0,20) #-- gives some data to use 
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
# Building matrix
# np.reshape(data, (no.of rows you want, no of col you want), order='__') 
# order = way in which matrix will be filled, 
#default is C, means rows are filled first
# F - columns are filled first
# NOTE: The C means C language, not columns

In [6]:
np.reshape(mydata,(5,4)) #NOTE: default order is Row first

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
np.reshape(mydata, (5,4), order='C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
# Go to the number 10 in the matrix
matr1 = np.reshape(mydata, (5,4), order='C')
matr1[2,2]

10

In [11]:
matr1 = np.reshape(mydata, (5,4), order='F')


In [12]:
matr1

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [13]:
type(mydata)

numpy.ndarray

In [14]:
# ANOTHER WAY
# use the data object directly instead of np
mydata.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
# -----------------

In [18]:
r1 = ["hello", "world"]
r2 = ["world", "doesn't", "care"]
r3 = [1,2,3]

In [19]:
[r1,r2,r3]

[['hello', 'world'], ['world', "doesn't", 'care'], [1, 2, 3]]

In [20]:
# TO develop a matrix from given lists
np.array([r1, r2, r3])

array([list(['hello', 'world']), list(['world', "doesn't", 'care']),
       list([1, 2, 3])], dtype=object)

In [23]:
print(np.array([r1, r2, r3]))

[list(['hello', 'world']) list(['world', "doesn't", 'care'])
 list([1, 2, 3])]
